version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

    cooldown:
      default-days: 7
      semver-patch-days: 3

    groups:
      dev-patch:
        dependency-type: "development"
        update-types: ["patch"]
      dev-minor:
        dependency-type: "development"
        update-types: ["minor"]
      prod-minor-patch:
        dependency-type: "production"
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns: ["*"]
